name: Tag Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Tests Before Tagging
      run: |
        sudo apt-get update
        sudo apt-get install -y antiword
        pip install -r requirements.txt
        pytest

    - name: Create Git Tag
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag ${{ github.event.inputs.tag }}
        git push origin ${{ github.event.inputs.tag }}

